FROM node:22-slim

WORKDIR /app

ENV NODE_ENV=development

COPY package*.json ./

RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY src ./src

EXPOSE 3000

CMD ["npm", "run", "start:dev"]

